### ISSUE TITLE
DIY Science Funding | Own business model

### ISSUE THREAD

**Issue by lucypatterson** [DIYScience/DIYScience#11]
**Each issue in this project will be flagged for attention in the Mozilla Global Sprint, 1-2nd June 2017. To help new contributors, please use this title format then copy+paste the following text for all new issues and fill in as apropriate - Thanks!**

This issue belongs to the [DIY Science Network](https://github.com/DIYScience/DIYScience): Connecting and supporting initiatives that engage with science from a grassroots, non-institutional position: diybio community labs, civic environmental monitoring projects, patient activism groups, bioart collectives, interdisciplinary science hacking communities...

PROJECT: "[How to get Funding](https://github.com/DIYScience/DIYScience/projects/4)"
We are gathering information and best practice on different modes and sources of funding for DIY science initiatives. This should give us a good overview of what kind of funding is available in different countries (and where there could be more), what it's like to access that funding, and what kind of projects we are using that funding for. Each issue represents one funding source/model.

### 1. Describe a funding source/model
For each new funding source we document, make a [new issue using this template](https://github.com/DIYScience/DIYScience/issues/1) (first check through the existing issues to make sure one doesn't already exist). You can also check this [brainstorm list](https://github.com/DIYScience/DIYScience/issues/1#issuecomment-302934191) for ideas.

+++++++++++++++++++
**FUNDING SOURCE/MODEL**: Sell stuff!
**DESCRIPTION**: Sell goods or services for profit and use that to support your project/space/DIYscience mission/lifestyle.
+++++++++++++++++++

### 2. Add comments
Please add information in the comments if you have experience with this kind of funding, good or bad. Alternatively, if you don't have personal experience, you can also help by researching others who have been funded this way. 

This is the kind of information we're looking for:
- NAME OF THE INITIATIVE (links, contacts, any relevant information about your status as an organisation etc):
- DESCRIPTION OF THE PROJECT (links etc):
- AMOUNT OF MONEY INVOLVED:
- COMMENTS:

Thanks!

**Comment by lucypatterson** [comment]
I'd love to hear from @PhilippBoeing on this one...
and @Winnieponcelet...

**Comment by Winnieponcelet** [comment]
FUNDING MODEL:
Workshops
Link (dutch): http://reagentlab.org/

DESCRIPTION: Host paid workshops. These can be repurposed to different target groups: children, general audience, artists/designers, companies (in order of how interesting they are financially). Children workshops probably need to be funded if they are in school context, as schools are generally poor. As an after school/weekend activity you can however at least pay the teacher a fair wage, but you will only get rich white children.
It takes some teaching skills to do this, which is often underestimated. Also takes basic marketing insight to find how to sell it to different target groups.

**Comment by Winnieponcelet** [comment]
FUNDING MODEL:
Science Communication trainings
Link: http://breakitdown.eu/
(there are also other business models on the website, but these are less directly connected I feel)

DESCRIPTION: trainings for researchers (storytelling, collaboration creativity, presentation techniques, ...). Being in the lab week after week, working with different audiences, one tends to get good at explaining science. Scientists/technical people are generally bad at explaining what they do (citizen scientists included actually).
This needs specific skills, people who are good communicators/teachers to begin with. The market is not that big, but it is a good baseline for people to support themselves.

**Comment by Winnieponcelet** [comment]
FUNDING MODEL:
Consultancy
Link: http://magmanova.com/

DESCRIPTION: when you are pioneering a research field, because institutions are too slow to adapt as quick as you are, you could get asked to do consultancy work. We only had one medium sized project, so just some preliminary lessons here. Here it really helps to have a seperate entity for the technology you are working with, so that communication about it does not get lost in communication about your space. 

We were in the news pretty often (so were other projects by our research team), we were (are) the only ones doing this research in our country and have a big network. This all helps in establishing our name as the go-to name for everything even remotely related to the technology, including companies seeking help. The research being kind of exotic and 'sensational' also helps. Even without many skills (we lacked many), the branding machine kept itself going in our case.

To secure a project, you'll need some project management skills / know general best practices for consultancy work and of course have some kind of legal company entity.

**Comment by lucypatterson** [comment]
@Winnieponcelet :1st_place_medal:  :) Could you perhaps edit to add some links to your different entities... thanks!

**Comment by jcolomb** [comment]
FUNDING MODEL:
Consultancy

In Germany, it works well when you can deliver something, in a "Werkvertrag". Since you can be working free lance as soon as you have a Steuernummer (tax number), you do not need an institution. I have been working for the university this way a couple of times (building a setup, building a code to analyse data, delivering a report, ...)

A bit more difficult, the "Diensleistungvertrag" is also possilble (organising a lecture, teaching,...). Be careful, in this case you should not be employed by the same lab and work there (it is illegal, they should hire you if you work for them for a long time on site).

**Comment by jcolomb** [comment]
FUNDING MODEL:
Workshops

Workshops (=teaching units) can be sold to graduate schools too, if you have something of interest. 
http://www.science-craft.com/

**Comment by lucypatterson** [comment]
Hey @Winnieponcelet - I did some restructuring of the project and (suggestion from @jcolomb) think it makes sense to break this issue down into separate issues for different business models. I'll repost your content :)
